const COLUMNS_BY_USER = [
    "id",
    "kind",
    "quarantineId",
    "result",
    "time",
    "times",
];
const EPID_FETCH = {
  content: [
    {
      id: 59,
      userId: 1234123123,
      des: "Khánh Trung",
      arrTime: "2020-12-02T00:00:00.000+00:00",
      vehicle: "Ô tô",
      vehCode: "aaaa",
      recentArr: "Bắc Giang",
      fever: false,
      cough: false,
      shortWinded: true,
      skinBlooded: false,
      pharmacy: "123213",
    },
    {
      id: 60,
      userId: 34200001001,
      des: "Hà Nội",
      arrTime: "2020-12-29T00:00:00.000+00:00",
      vehicle: "Xe Máy",
      vehCode: "18V1 5481",
      recentArr: "Bắc Giang",
      fever: true,
      cough: false,
      shortWinded: false,
      skinBlooded: false,
      pharmacy: "Thuốc ho",
    },
    {
      id: 61,
      userId: 34200001002,
      des: "Hà Nội",
      arrTime: "2020-12-29T00:00:00.000+00:00",
      vehicle: "Xe Máy",
      vehCode: "17B1 5481",
      recentArr: "Thái Bình",
      fever: true,
      cough: false,
      shortWinded: true,
      skinBlooded: true,
      pharmacy: "Thuốc hạ sốt",
    },
    {
      id: 62,
      userId: 34200001003,
      des: "Hải Phòng",
      arrTime: "2020-12-29T00:00:00.000+00:00",
      vehicle: "Xe Máy",
      vehCode: "23B1 5481",
      recentArr: "Quảng Ninh",
      fever: true,
      cough: true,
      shortWinded: true,
      skinBlooded: true,
      pharmacy: "Thuốc ho, thuốc hạ sốt",
    },
    {
      id: 63,
      userId: 34200001004,
      des: "Hải Phòng",
      arrTime: "2020-12-29T00:00:00.000+00:00",
      vehicle: "Xe Máy",
      vehCode: "23B1 5481",
      recentArr: "Quảng Ninh",
      fever: true,
      cough: true,
      shortWinded: false,
      skinBlooded: true,
      pharmacy: "Thuốc dạ dày",
    },
    {
      id: 64,
      userId: 34200001005,
      des: "Ha Tinh",
      arrTime: "2020-10-29T00:00:00.000+00:00",
      vehicle: "Xe Máy",
      vehCode: "23B1 1322",
      recentArr: "Quảng Ninh",
      fever: true,
      cough: false,
      shortWinded: false,
      skinBlooded: true,
      pharmacy: "Thuốc đau đầu",
    },
    {
      id: 65,
      userId: 34200001006,
      des: "Quảng Nam",
      arrTime: "2020-11-23T00:00:00.000+00:00",
      vehicle: "Tàu Hỏa",
      vehCode: "54B1 1322",
      recentArr: "Quảng Ninh",
      fever: false,
      cough: false,
      shortWinded: false,
      skinBlooded: false,
      pharmacy: "Không dùng thuốc ",
    },
    {
      id: 66,
      userId: 34200001007,
      des: "Quảng Nam",
      arrTime: "2020-11-23T00:00:00.000+00:00",
      vehicle: "Tàu Hỏa",
      vehCode: "54D1 6575",
      recentArr: "Quảng Ninh",
      fever: false,
      cough: false,
      shortWinded: false,
      skinBlooded: false,
      pharmacy: "Không dùng thuốc ",
    },
    {
      id: 67,
      userId: 34200001008,
      des: "Quảng Nam",
      arrTime: "2020-11-05T00:00:00.000+00:00",
      vehicle: "Tàu Hỏa",
      vehCode: "55F5 3563",
      recentArr: "Quảng Ninh",
      fever: false,
      cough: true,
      shortWinded: false,
      skinBlooded: true,
      pharmacy: "Thuốc giảm đau",
    },
    {
      id: 68,
      userId: 34200001009,
      des: "Ha Giang",
      arrTime: "2020-11-05T00:00:00.000+00:00",
      vehicle: "Tàu Hỏa",
      vehCode: "55F5 5463",
      recentArr: "Quảng Ninh",
      fever: false,
      cough: true,
      shortWinded: true,
      skinBlooded: true,
      pharmacy: "Thuốc hạ sốt",
    },
    {
      id: 69,
      userId: 34200001010,
      des: "Quảng Ninh",
      arrTime: "2020-11-03T00:00:00.000+00:00",
      vehicle: "Tàu Hỏa",
      vehCode: "55F5 1323",
      recentArr: "Quảng Ninh",
      fever: false,
      cough: true,
      shortWinded: false,
      skinBlooded: true,
      pharmacy: "Thuốc hạ sốt",
    },
    {
      id: 70,
      userId: 34200001011,
      des: "Quang Binh",
      arrTime: "2020-11-03T00:00:00.000+00:00",
      vehicle: "Ô tô",
      vehCode: "53T5 1323",
      recentArr: "Ha Nam",
      fever: false,
      cough: true,
      shortWinded: true,
      skinBlooded: true,
      pharmacy: "Thuốc đau đầu",
    },
    {
      id: 71,
      userId: 34200001012,
      des: "Quang Binh",
      arrTime: "2020-11-05T00:00:00.000+00:00",
      vehicle: "Ô tô",
      vehCode: "53T5 1288",
      recentArr: "Ha Nam",
      fever: false,
      cough: true,
      shortWinded: false,
      skinBlooded: true,
      pharmacy: "Thuốc hạ sốt",
    },
    {
      id: 72,
      userId: 34200001013,
      des: "Quảng Nam",
      arrTime: "2020-11-05T00:00:00.000+00:00",
      vehicle: "Ô tô",
      vehCode: "53Y5 1256",
      recentArr: "Da Nang",
      fever: false,
      cough: true,
      shortWinded: false,
      skinBlooded: true,
      pharmacy: "Thuốc hạ sốt",
    },
    {
      id: 73,
      userId: 34200001014,
      des: "Quảng Nam",
      arrTime: "2020-11-05T00:00:00.000+00:00",
      vehicle: "Ô tô",
      vehCode: "12Y5 1256",
      recentArr: "Da Nang",
      fever: false,
      cough: true,
      shortWinded: false,
      skinBlooded: true,
      pharmacy: "Thuốc hạ sốt",
    },
    {
      id: 74,
      userId: 34200001015,
      des: "Hoa Binh",
      arrTime: "2020-11-05T00:00:00.000+00:00",
      vehicle: "Ô tô",
      vehCode: "12B2 1256",
      recentArr: "Da Nang",
      fever: true,
      cough: true,
      shortWinded: false,
      skinBlooded: true,
      pharmacy: "Thuốc hạ sốt",
    },
  ],
  pageable: {
    sort: {
      sorted: false,
      unsorted: true,
      empty: true,
    },
    offset: 0,
    pageNumber: 0,
    pageSize: 20,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 18,
  last: true,
  size: 20,
  number: 0,
  sort: {
    sorted: false,
    unsorted: true,
    empty: true,
  },
  numberOfElements: 18,
  first: true,
  empty: false,
};
const HEALTH_FETCH = {
  content: [
    {
      id: 1237,
      userId: 34200001001,
      insurranceId: "12341001",
      fever: true,
      cough: true,
      shortWinded: true,
      pneumonia: true,
      soreThroat: true,
      tired: true,
      chronicLiver: true,
      chronicBlood: true,
      chronicLung: true,
      chronicKidney: true,
      heartRelatedDiseases: true,
    },
    {
      id: 1238,
      userId: 34200001002,
      insurranceId: "12341002",
      fever: true,
      cough: true,
      shortWinded: true,
      pneumonia: false,
      soreThroat: true,
      tired: false,
      chronicLiver: true,
      chronicBlood: true,
      chronicLung: true,
      chronicKidney: false,
      heartRelatedDiseases: true,
    },
    {
      id: 1239,
      userId: 34200001003,
      insurranceId: "12341003",
      fever: false,
      cough: true,
      shortWinded: false,
      pneumonia: false,
      soreThroat: true,
      tired: true,
      chronicLiver: true,
      chronicBlood: true,
      chronicLung: true,
      chronicKidney: false,
      heartRelatedDiseases: true,
    },
    {
      id: 1240,
      userId: 34200001004,
      insurranceId: "12341004",
      fever: false,
      cough: true,
      shortWinded: true,
      pneumonia: true,
      soreThroat: true,
      tired: true,
      chronicLiver: true,
      chronicBlood: true,
      chronicLung: true,
      chronicKidney: false,
      heartRelatedDiseases: true,
    },
    {
      id: 1241,
      userId: 34200001005,
      insurranceId: "12341005",
      fever: false,
      cough: true,
      shortWinded: true,
      pneumonia: true,
      soreThroat: true,
      tired: true,
      chronicLiver: true,
      chronicBlood: true,
      chronicLung: true,
      chronicKidney: false,
      heartRelatedDiseases: true,
    },
    {
      id: 1242,
      userId: 34200001006,
      insurranceId: "12341006",
      fever: false,
      cough: false,
      shortWinded: false,
      pneumonia: false,
      soreThroat: false,
      tired: false,
      chronicLiver: false,
      chronicBlood: false,
      chronicLung: true,
      chronicKidney: false,
      heartRelatedDiseases: true,
    },
    {
      id: 1243,
      userId: 34200001007,
      insurranceId: "12341007",
      fever: true,
      cough: false,
      shortWinded: true,
      pneumonia: false,
      soreThroat: false,
      tired: true,
      chronicLiver: false,
      chronicBlood: false,
      chronicLung: true,
      chronicKidney: false,
      heartRelatedDiseases: true,
    },
    {
      id: 1244,
      userId: 34200001008,
      insurranceId: "12341008",
      fever: true,
      cough: true,
      shortWinded: true,
      pneumonia: true,
      soreThroat: false,
      tired: true,
      chronicLiver: false,
      chronicBlood: false,
      chronicLung: true,
      chronicKidney: false,
      heartRelatedDiseases: true,
    },
    {
      id: 1245,
      userId: 34200001009,
      insurranceId: "12341009",
      fever: true,
      cough: true,
      shortWinded: false,
      pneumonia: false,
      soreThroat: false,
      tired: true,
      chronicLiver: true,
      chronicBlood: true,
      chronicLung: true,
      chronicKidney: false,
      heartRelatedDiseases: true,
    },
    {
      id: 1246,
      userId: 34200001010,
      insurranceId: "12341010",
      fever: true,
      cough: true,
      shortWinded: false,
      pneumonia: false,
      soreThroat: false,
      tired: true,
      chronicLiver: true,
      chronicBlood: true,
      chronicLung: true,
      chronicKidney: true,
      heartRelatedDiseases: true,
    },
    {
      id: 1247,
      userId: 34200001011,
      insurranceId: "12341011",
      fever: false,
      cough: false,
      shortWinded: false,
      pneumonia: false,
      soreThroat: false,
      tired: true,
      chronicLiver: true,
      chronicBlood: true,
      chronicLung: true,
      chronicKidney: false,
      heartRelatedDiseases: false,
    },
    {
      id: 1248,
      userId: 34200001012,
      insurranceId: "12341012",
      fever: false,
      cough: false,
      shortWinded: true,
      pneumonia: false,
      soreThroat: false,
      tired: true,
      chronicLiver: true,
      chronicBlood: true,
      chronicLung: true,
      chronicKidney: false,
      heartRelatedDiseases: false,
    },
    {
      id: 1249,
      userId: 34200001013,
      insurranceId: "12341013",
      fever: true,
      cough: true,
      shortWinded: true,
      pneumonia: false,
      soreThroat: false,
      tired: true,
      chronicLiver: true,
      chronicBlood: true,
      chronicLung: true,
      chronicKidney: false,
      heartRelatedDiseases: false,
    },
    {
      id: 1250,
      userId: 34200001014,
      insurranceId: "12341014",
      fever: true,
      cough: true,
      shortWinded: true,
      pneumonia: false,
      soreThroat: false,
      tired: true,
      chronicLiver: true,
      chronicBlood: true,
      chronicLung: true,
      chronicKidney: false,
      heartRelatedDiseases: false,
    },
    {
      id: 1251,
      userId: 34200001015,
      insurranceId: "12341015",
      fever: true,
      cough: true,
      shortWinded: true,
      pneumonia: true,
      soreThroat: false,
      tired: true,
      chronicLiver: true,
      chronicBlood: true,
      chronicLung: true,
      chronicKidney: false,
      heartRelatedDiseases: false,
    },
  ],
  pageable: {
    sort: { sorted: false, unsorted: true, empty: true },
    offset: 0,
    pageNumber: 0,
    pageSize: 20,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 15,
  last: true,
  size: 20,
  number: 0,
  sort: { sorted: false, unsorted: true, empty: true },
  numberOfElements: 15,
  first: true,
  empty: false,
};
export { COLUMNS_BY_USER, EPID_FETCH, HEALTH_FETCH };
